### ISSUE TITLE
[Bug] KeyError: u'ISO' on creating custom map

### ISSUE THREAD

**Issue by elvismdev** [10bestdesign/jqvmap#325]
I get this error when trying to [create a custom map](https://github.com/elvismdev/jqvmap/tree/master/create)

`python jqvmap.py config/country-name.json`

```
Traceback (most recent call last):
  File "jqvmap.py", line 575, in <module>
    processor.process()
  File "jqvmap.py", line 478, in process
    getattr(self, action['name'])( action, self.data_sources.get(".") )
  File "jqvmap.py", line 485, in write_data
    data_source.output( config )
  File "jqvmap.py", line 299, in output
    self.output_jvm(output)
  File "jqvmap.py", line 346, in output_jvm
    converter.convert(self, output['file_name'])
  File "jqvmap.py", line 115, in convert
    codes = map(lambda g: g.properties[self.config['code_field']], data_source.geometries)
  File "jqvmap.py", line 115, in <lambda>
    codes = map(lambda g: g.properties[self.config['code_field']], data_source.geometries)
KeyError: u'ISO'
```
Country config json:

```json
// config/country-name.json

[
  {
    "name": "read_data",
    "file_name": "./source/gadm36_CUB_shp/gadm36_CUB_0.shp"
  },
  {
    "name": "write_data",
    "format": "jqvmap",
    "file_name": "./output/jquery.vmap.country-name.js",
    "params": {
      "code_field": "ISO",
      "name_field": "NAME_ENGLI",
      "name": "country-name"
    }
  }
]
```

My system:
- Python 2.7.12
- GDAL 2.1.3
- Shapely 1.2.16
- Booleano 1.1a2
  - pyparsing 2.2.0
  - six 1.10.0

Is this a bug or I'm missing something?

**Comment by 21f1nger** [comment]
I have the same problem. Help me please.

**Comment by ricardomx** [comment]
Open .DBF in a directory on your shapefiles, openoffice works. you see the first and secod column names, something this:


GID_0,C,80 | NAME_0,C,80 | GID_1,C,80 | NAME_1,C,80
-- | -- | -- | --
MEX | Mexico | MEX.1_1 | Aguascalientes
MEX | Mexico | MEX.3_1 | Baja California
MEX | Mexico | MEX.2_1 | Baja California Sur
MEX | Mexico | MEX.4_1 | Campeche



only use in first parameter GID_0 (whitout commas)
and teh secod parameter NAME_0 (whitout commas)

```
"params": {
      "code_field": "GID_0",
      "name_field": "NAME_0",
      "name": "mexico"
    }
```

this works for me.



<img width="296" alt="Captura de Pantalla 2019-05-25 a la(s) 11 30 52" src="https://user-images.githubusercontent.com/9216420/58372312-0d74a380-7ee1-11e9-8b76-d7b20e2c4424.png">
